# Default values for freshrss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: freshrss/freshrss
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

freshrss:
  # freshrss.cron_min -- What minutes of the hour should the cron script run
  cron_min: [23, 53]

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: freshrss.kitties.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: freshrss-tls 
      hosts:
        - freshrss.kitties.dev

namespace:
  name: news

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "longhorn-bbq"
  accessMode: ReadWriteOnce
  size: 1G
  # if you need any additional volumes, you can define them here
  additionalVolumes: []
  # if you need any additional volume mounts, you can define them here
  additionalMounts: []
